rm(list=ls())
library(readr)

NYPD_Arrest <- read_csv("data-raw/NYPD_Arrest_Data_2023.csv")

# setup to use only the columns I plan to use
selected_columns <- c('ARREST_DATE', 'OFNS_DESC', 'LAW_CAT_CD', 'ARREST_BORO', 'JURISDICTION_CODE', 'AGE_GROUP', 'PERP_SEX', 'PERP_RACE', 'Latitude', 'Longitude')
NYPD_Arrest <- NYPD_Arrest[selected_columns]

# Convert ARREST_DATE to Date format
NYPD_Arrest$ARREST_DATE <- as.Date(NYPD_Arrest$ARREST_DATE, format = "%m/%d/%Y")

# Check unique values in categorical variables
sapply(NYPD_Arrest[, c("OFNS_DESC", "LAW_CAT_CD", "ARREST_BORO", "PERP_SEX", "PERP_RACE")], unique)

# # Filter out invalid values in LAW_CAT_CD
valid_law_cat <- c('F', 'M', 'V')
NYPD_Arrest <- NYPD_Arrest[NYPD_Arrest$LAW_CAT_CD %in% valid_law_cat, ]

# Check unique values in LAW_CAT_CD after filtering
# should only print out 'F' 'M' and 'V'
unique(NYPD_Arrest$LAW_CAT_CD)

# change variables into factors
NYPD_Arrest$LAW_CAT_CD <- as.factor(NYPD_Arrest$LAW_CAT_CD)
NYPD_Arrest$ARREST_BORO <- as.factor(NYPD_Arrest$ARREST_BORO)
NYPD_Arrest$AGE_GROUP <- as.factor(NYPD_Arrest$AGE_GROUP)
NYPD_Arrest$PERP_SEX <- as.factor(NYPD_Arrest$PERP_SEX)
NYPD_Arrest$PERP_RACE <- as.factor(NYPD_Arrest$PERP_RACE)


# combine a bunch of the factors in OFNS_DESC to more generalized factors for less factors overall
category_mapping <- c(
  "FELONY ASSAULT" = "ASSAULT",
  "DANGEROUS DRUGS" = "DRUGS",
  "RAPE" = "SEX CRIMES",
  "FORGERY" = "FRAUD",
  "BURGLARY" = "BURGLARY",
  "ARSON" = "ARSON",
  "ASSAULT 3 & RELATED OFFENSES" = "ASSAULT",
  "ROBBERY" = "ROBBERY",
  "PETIT LARCENY" = "LARCENY",
  "DANGEROUS WEAPONS" = "WEAPONS",
  "MISCELLANEOUS PENAL LAW" = "OTHER PENAL LAW",
  "HARRASSMENT 2" = "HARRASSMENT",
  "OFF. AGNST PUB ORD SENSBLTY &" = "PUBLIC ORDER OFFENSES",
  "JOSTLING" = "ASSAULT",
  "SEX CRIMES" = "SEX CRIMES",
  "FRAUDS" = "FRAUD",
  "ESCAPE 3" = "ESCAPE",
  "BURGLAR'S TOOLS" = "BURGLARY",
  "VEHICLE AND TRAFFIC LAWS" = "TRAFFIC",
  "OFFENSES AGAINST THE PERSON" = "OTHER OFFENSES",
  "OFFENSES INVOLVING FRAUD" = "FRAUD",
  "INTOXICATED & IMPAIRED DRIVING" = "TRAFFIC",
  "OTHER OFFENSES RELATED TO THEF" = "OTHER OFFENSES",
  "POSSESSION OF STOLEN PROPERTY" = "PROPERTY CRIME",
  "OTHER TRAFFIC INFRACTION" = "TRAFFIC",
  "GRAND LARCENY" = "LARCENY",
  "CRIMINAL MISCHIEF & RELATED OF" = "OTHER OFFENSES",
  "OTHER STATE LAWS (NON PENAL LA" = "OTHER OFFENSES",
  "PROSTITUTION & RELATED OFFENSES" = "PROSTITUTION",
  "GAMBLING" = "OTHER OFFENSES",
  "CRIMINAL TRESPASS" = "TRESPASS",
  "OFFENSES AGAINST PUBLIC ADMINI" = "PUBLIC ORDER OFFENSES",
  "MURDER & NON-NEGL. MANSLAUGHTE" = "HOMICIDE",
  "OTHER STATE LAWS" = "OTHER OFFENSES",
  "CANNABIS RELATED OFFENSES" = "DRUGS",
  "NYS LAWS-UNCLASSIFIED FELONY" = "OTHER OFFENSES",
  "OFFENSES AGAINST PUBLIC SAFETY" = "PUBLIC ORDER OFFENSES",
  "GRAND LARCENY OF MOTOR VEHICLE" = "LARCENY",
  "UNAUTHORIZED USE OF A VEHICLE" = "TRAFFIC",
  "ADMINISTRATIVE CODE" = "OTHER OFFENSES",
  "OFFENSES RELATED TO CHILDREN" = "OTHER OFFENSES",
  "THEFT-FRAUD" = "FRAUD",
  "INTOXICATED/IMPAIRED DRIVING" = "TRAFFIC",
  "ANTICIPATORY OFFENSES" = "OTHER OFFENSES",
  "FRAUDULENT ACCOSTING" = "FRAUD",
  "THEFT OF SERVICES" = "LARCENY",
  "ENDAN WELFARE INCOMP" = "OTHER OFFENSES",
  "OTHER STATE LAWS (NON PENAL LAW)" = "OTHER OFFENSES",
  "ALCOHOLIC BEVERAGE CONTROL LAW" = "OTHER OFFENSES",
  "DISORDERLY CONDUCT" = "DISORDERLY CONDUCT",
  "KIDNAPPING & RELATED OFFENSES" = "KIDNAPPING",
  "AGRICULTURE & MRKTS LAW-UNCLASSIFIED" = "OTHER OFFENSES",
  "HOMICIDE-NEGLIGENT,UNCLASSIFIE" = "HOMICIDE",
  "CHILD ABANDONMENT/NON SUPPORT" = "OTHER OFFENSES",
  "KIDNAPPING" = "KIDNAPPING",
  "UNLAWFUL POSS. WEAP. ON SCHOOL" = "WEAPONS",
  "DISRUPTION OF A RELIGIOUS SERV" = "OTHER OFFENSES",
  "HOMICIDE-NEGLIGENT-VEHICLE" = "HOMICIDE",
  "FELONY SEX CRIMES" = "SEX CRIMES",
  "ADMINISTRATIVE CODES" = "OTHER OFFENSES"
)
NYPD_Arrest$OFNS_DESC <- as.factor(category_mapping[as.character(NYPD_Arrest$OFNS_DESC)])

str(NYPD_Arrest)

# check if there is any NULL's in the data and clean them out
sapply(NYPD_Arrest, function(x) sum(is.na(x)))
NYPD_Arrest <- na.omit(NYPD_Arrest)

usethis::use_data(NYPD_Arrest, overwrite=TRUE)

